#!/bin/sh

#kp: 3/4/17: Copied from https://coderwall.com/p/mnwcog/create-new-github-repo-from-command-line
#    With this, we can create a new repo in github from the command line as follows:
#       git create mynewrepo
#
#   Alternatively, we can go to github webpage itself and create the directory.
#
#    3/29/17: Actually, I need to run it as follows:
#
#     ./git-create mynewrepo
#    

repo_name=$1
test -z $repo_name && echo "Repo name required." 1>&2 && exit 1

#curl -u 'your_github_username' https://api.github.com/user/repos -d "{\"name\":\"$repo_name\"}"
curl -u 'ShivaramKPA' https://api.github.com/user/repos -d "{\"name\":\"$repo_name\"}"
